version: '3.7'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        ports:
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    database:
        hostname: postgres
        image: postgres:latest
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
    redis:
        hostname: redis
        image: redis:latest
        ports:
            - "6379:6379"


    scheduler:
        build:
            context: .
            target: scheduler
        volumes:
            - .:/usr/src/app
        links:
            - rabbit
            - database
            - redis
        depends_on:
            - database
            - rabbit
            - redis

    api-server:
        build: 
            context: .
            target: api-server
        volumes:
            - .:/usr/src/app
        links:
            - rabbit
            - database
            - redis
        depends_on:
            - database
            - rabbit
            - redis
        ports:
            - "5000:80"
